// <auto-generated />
namespace StockScreener2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbupdate13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbupdate13));
        
        string IMigrationMetadata.Id
        {
            get { return "201610091850271_dbupdate13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
