// <auto-generated />
namespace StockScreener2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dbupdate4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbupdate4));
        
        string IMigrationMetadata.Id
        {
            get { return "201608291929196_dbupdate4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
